In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [2]:
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=True)
print(linear(sample))

#y=Wx+b (linear) ; here, 3 ip blocks and 3 op ;
#bias = false (b=0, so y=Wx) 


tensor([-5.5034, -5.2999,  8.1972], grad_fn=<ViewBackward0>)


In [3]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

# e = 2.71 
# e^1 = 2.71 , e^2 = 7.34 , e^3 = 19.9
# 2.71 + 7.34 + 19.9 = 29.95
# pos 0 = 2.71/29.95   = 0.09
# pos 1 = 7.34 / 29.95 = 
# pos 2 = 19.9 / 29.95 = 

tensor([0.0900, 0.2447, 0.6652])


In [4]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b) #dot prod 
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [5]:
# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[ 4.5672e-01,  1.3719e+00,  2.7077e-01, -1.1813e+00,  3.8220e-01,
          8.8140e-01],
        [-5.3833e-01,  1.2491e+00, -8.1686e-01,  1.2376e+00, -1.5172e+00,
          4.8032e-02],
        [-5.7799e-01, -7.8272e-01,  9.6753e-01,  2.4541e-01, -1.1820e-02,
         -2.7692e-01],
        [ 1.1358e-03,  6.9464e-01,  4.9302e-01, -1.6990e+00,  2.8588e-01,
          9.5510e-02]], grad_fn=<EmbeddingBackward0>)


In [9]:
x = torch.tensor([5], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([0.9999])
