In [1]:
import torch 
import torch
import numpy as np
import time

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
torch.cuda.synchronize()

cuda


In [3]:
torch_rand1 = torch.rand(100, 100, 100, 100, device=device)
torch_rand2 = torch.rand(100, 100, 100, 100, device=device)
start_time = time.time()
rand_torch = torch_rand1 @ torch_rand2
end_time = time.time()
print(f"PyTorch (GPU) time: {end_time - start_time:.8f} seconds")


np_rand1 = np.random.rand(100, 100, 100, 100).astype(np.float32)
np_rand2 = np.random.rand(100, 100, 100, 100).astype(np.float32)
start_time = time.time()
rand_np = np.matmul(np_rand1, np_rand2)
end_time = time.time()
print(f"NumPy (CPU) time: {end_time - start_time:.6f} seconds")

PyTorch (GPU) time: 0.47367477 seconds
NumPy (CPU) time: 2.403978 seconds


In [4]:
# Define a probability tensor
# 10% or 0.1 => 0 ; 90% or 0.9 => 1.
probabilities = torch.tensor([0.1, 0.9])

# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 0, 1, 1, 1])


In [5]:
tensor1 = torch.tensor([1, 2, 3, 4])
tensor2 = torch.tensor([5, 6, 1, 4])
out = torch.cat((tensor1, tensor2), dim=0)
out

tensor([1, 2, 3, 4, 5, 6, 1, 4])

In [6]:
out = torch.tril(torch.ones(5, 5)) #set everything above the diagonal as false
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [7]:
out = torch.triu(torch.ones(5, 5)) #set everything below the diagonal as false
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [8]:
out = torch.zeros(5, 5).masked_fill( #5x5 zero
    torch.tril(torch.ones(5, 5)) == 0, # trail keeps elements on and below the main diagonal, sets everything above it to 0
                                       #==0 creats a T/F boolean matrix (5x5)
    float('-inf')                      #Wherever mask == True, replace value with -∞
)
out
#Prevent a token from “seeing” future tokens

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [9]:
input = torch.zeros(2, 3, 4)
out1 = input.transpose(0, 1) #swap 0 and 1
out2 = input.transpose(-2,-1) #swap -2(pos 1 =3) with -1(pos 2=4)
print(out1.shape)
print(out2.shape)

torch.Size([3, 2, 4])
torch.Size([2, 4, 3])


In [10]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])