In [4]:
import torch 

In [57]:
randit = torch.randint(-100,100,(6,))
randit

tensor([-10,  34, -55,  82, -99,  23])

In [60]:
tensor = torch.tensor([[0.1 , 1.2] , [2.2,3.1], [4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [64]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [65]:
ones = torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [75]:
arrange = torch.arange(5)
arrange

tensor([0, 1, 2, 3, 4])

In [77]:
linspace = torch.linspace(3,10,steps = 5) 
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [78]:
logspace = torch.logspace(start=-10, end = 10 , steps = 5) 
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [82]:
eye = torch.eye (5) #I(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])